interpolate-creds: &interpolate-creds
  image: platform-automation-image
  file: platform-automation-tasks/tasks/credhub-interpolate.yml
  params:
    CREDHUB_CLIENT: credhub_admin
    CREDHUB_SECRET: ((credhub-secret))
    CREDHUB_SERVER: ((credhub-server))
    CREDHUB_CA_CERT: ((credhub-ca-cert))
    PREFIX: '/pks/test'
    SKIP_MISSING: true
  input_mapping:
    files: configuration
  output_mapping:
    interpolated-files: interpolated-creds

resource_types:
- name: azure-blobstore
  type: docker-image
  source:
    repository: pcfabr/azure-blobstore-resource

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: configuration
  type: git
  source:
    private_key: ((github_private_key))
    uri: git@github.com:EngineerBetter/pa_pks_azure.git
    branch: master

- name: installation
  type: azure-blobstore
  source:
    storage_account_name: ((storage_account_name))
    storage_account_key: ((storage_account_key))
    container: resources
    regexp: pks-installation-(.*).zip

- name: state
  type: azure-blobstore
  source:
    storage_account_name: ((storage_account_name))
    storage_account_key: ((storage_account_key))
    container: resources
    regexp: state-pks-(.*).yml

- name: platform-automation
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    product_version: 4\.(.*)
    sort_by: semver

- name: ops-manager
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ops-manager
    product_version: 2\.6\.(.*)
    sort_by: semver

- name: pks
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: pivotal-container-service
    product_version: 1\.5\.(.*)
    sort_by: semver

- name: pks-stemcell
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: stemcells-ubuntu-xenial
    product_version: 315\.(.*)
    sort_by: semver

- name: one-time-trigger
  type: time
  source:
    interval: 999999h

- name: daily-trigger
  type: time
  source:
    interval: 24h

jobs:
- name: install-opsman
  serial: true
  serial_groups: [ install ]
  plan:
    - in_parallel:
      - get: one-time-trigger
        trigger: true
      - get: platform-automation-image
        resource: platform-automation
        params:
          unpack: true
          globs:
          - "*.tgz"
      - get: platform-automation-tasks
        resource: platform-automation
        params:
          globs:
          - "*.zip"
          unpack: true
      - get: ops-manager
        params:
          globs:
          - "ops-manager-azure-*.yml"
      - get: configuration
      - get: state
    - task: interpolate-creds
      <<: *interpolate-creds
    - task: create-vm
      image: platform-automation-image
      file: platform-automation-tasks/tasks/create-vm.yml
      input_mapping:
        image: ops-manager
        config: interpolated-creds
      params:
        STATE_FILE: state-pks.yml
      ensure: &put-state
        do:
        - put: state
          params:
            file: generated-state/state-pks.yml
    - task: configure-authentication
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-authentication.yml
      attempts: 10
      input_mapping:
        env: interpolated-creds
        config: interpolated-creds
    - task: configure-director
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-director.yml
      input_mapping:
        config: interpolated-creds
        env: interpolated-creds
    - task: apply-director-changes
      image: platform-automation-image
      file: platform-automation-tasks/tasks/apply-director-changes.yml
      input_mapping:
        env: interpolated-creds

- name: export-installation
  serial: true
  plan:
    - in_parallel:
      - get: daily-trigger
        trigger: true
      - get: state
        passed:
        - install-opsman
      - get: platform-automation-image
        resource: platform-automation
        params:
          unpack: true
          globs:
          - "*.tgz"
      - get: platform-automation-tasks
        resource: platform-automation
        params:
          globs:
          - "*.zip"
          unpack: true
          passed: [ install-opsman ]
      - get: configuration
        trigger: true
    - task: interpolate-creds
      <<: *interpolate-creds
    - task: export-installation
      image: platform-automation-image
      file: platform-automation-tasks/tasks/export-installation.yml
      input_mapping:
        env: interpolated-creds
      params:
        INSTALLATION_FILE: pks-installation-$timestamp.zip
    - put: installation
      params:
        file: installation/pks-installation*.zip

- name: upgrade-opsman
  serial: true
  serial_groups: [ install ]
  plan:
  - in_parallel:
    - get: platform-automation-image
      resource: platform-automation
      params:
        unpack: true
        globs:
        - "*.tgz"
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        globs:
        - "*.zip"
        unpack: true
    - get: installation
      passed: [ export-installation ]
    - get: configuration
      trigger: true
      passed:
      - export-installation
    - get: state
    - get: ops-manager
      params:
        globs:
        - "ops-manager-azure-*.yml"
  - task: interpolate-creds
    <<: *interpolate-creds
  - task: upgrade-opsman
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upgrade-opsman.yml
    input_mapping:
      image: ops-manager
      config: interpolated-creds
      env: interpolated-creds
    params:
      STATE_FILE: state-pks.yml
      INSTALLATION_FILE: pks-installation*.zip
    ensure: *put-state
  - task: configure-director
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-director.yml
    input_mapping:
      config: interpolated-creds
      env: interpolated-creds
  - task: apply-director-changes
    image: platform-automation-image
    file: platform-automation-tasks/tasks/apply-director-changes.yml
    input_mapping:
      env: interpolated-creds

- name: upload-and-stage-pks
  serial: true
  plan:
    - in_parallel:
      - get: platform-automation-image
        resource: platform-automation
        params:
          unpack: true
          globs:
          - "*.tgz"
      - get: platform-automation-tasks
        resource: platform-automation
        params:
          globs:
          - "*.zip"
          unpack: true
      - get: configuration
        trigger: true
        passed:
        - upgrade-opsman
      - get: pks
        params:
          globs:
          - "*.pivotal"
      - get: pks-stemcell
        params:
          globs:
          - "bosh-stemcell-*-azure-hyperv-ubuntu-xenial-go_agent.tgz"
    - task: interpolate-creds
      <<: *interpolate-creds
    - task: upload-and-stage-product
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-and-stage-product.yml
      input_mapping:
        product: pks
        env: interpolated-creds
    - task: upload-pks-stemcell
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-stemcell.yml
      input_mapping:
        env: interpolated-creds
        stemcell: pks-stemcell

- name: configure-pks
  serial: true
  plan:
    - in_parallel:
      - get: platform-automation-image
        resource: platform-automation
        params:
          unpack: true
          globs:
          - "*.tgz"
      - get: platform-automation-tasks
        resource: platform-automation
        params:
          globs:
          - "*.zip"
          unpack: true
      - get: configuration
        trigger: true
        passed:
        - upload-and-stage-pks
    - task: interpolate-creds
      <<: *interpolate-creds
    - task: configure-pks
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-product.yml
      input_mapping:
        config: interpolated-creds
        env: interpolated-creds
      params:
        CONFIG_FILE: pks.yml

- name: apply-product-changes
  serial: true
  plan:
    - in_parallel:
      - get: platform-automation-image
        resource: platform-automation
        params:
          unpack: true
          globs:
          - "*.tgz"
      - get: platform-automation-tasks
        resource: platform-automation
        params:
          globs:
          - "*.zip"
          unpack: true
      - get: configuration
        trigger: true
        passed:
        - configure-pks
    - task: interpolate-creds
      <<: *interpolate-creds
    - task: apply-product-changes
      image: platform-automation-image
      file: platform-automation-tasks/tasks/apply-changes.yml
      input_mapping:
        env: interpolated-creds
