---
opsman-configuration:
  azure:
    subscription_id: ((subscription_id))
    resource_group: pks
    tenant_id: ((tenant_id))
    client_id: ((client_id))
    client_secret: ((client_secret))
    location: uksouth
    container: opsmanagerimage                    # container for opsman image
    network_security_group: pks-ops-manager-security-group

    # Note that there are several environment-specific details in this path
    vpc_subnet: /subscriptions/((subscription_id))/resourceGroups/pks/providers/Microsoft.Network/virtualNetworks/pks-virtual-network/subnets/pks-infrastructure-subnet

    storage_account: ((ops_man_storage_account))

    ssh_public_key: ((ops_man_public_key))
    vm_name: ops-manager-vm                       # default: Ops Manager-vm
    boot_disk_size: 100                           # default: 200
    cloud_name: AzureCloud                        # default: AzureCloud

    # This flag is only respected by the create-vm & upgrade-opsman commands
    # set to true if you want to create the new opsman vm with unmanaged disk
    # delete-vm discovers the disk type from the VM
    use_unmanaged_disk: false

    # At least one IP address (public or private)
    # needs to be assigned to the VM.
    # It is also permissable to assign both.
    public_ip: 51.140.102.14
    private_ip: 10.0.8.4
